name: Dummy
on:
  pull_request:


jobs:
  get-pr-number:
    name: Get PR number
    uses: ./.github/workflows/self-get-pr-number.yml

  show-pr-number:
    runs-on: ubuntu-22.04
    needs: get-pr-number
    steps:
      - run: echo ${{ needs.get-pr-number.outputs.PR_NUMBER }}

  get-pr-sha:
    name: Get PR commit SHA
    needs: get-pr-number
    if: ${{ needs.get-pr-number.outputs.PR_NUMBER != ''}}
    uses: ./.github/workflows/self-get-pr-sha.yml
    with:
      pr_number: ${{ needs.get-pr-number.outputs.PR_NUMBER }}

  show-pr-sha:
    runs-on: ubuntu-22.04
    needs: get-pr-sha
    steps:
      - run: |
          echo ${{ needs.get-pr-sha.outputs.PR_HEAD_SHA_BAD }}
          echo ${{ needs.get-pr-sha.outputs.PR_MERGE_SHA_BAD }}
          echo ${{ needs.get-pr-sha.outputs.PR_HEAD_REPO_FULL_NAME }}
          echo ${{ needs.get-pr-sha.outputs.PR_BASE_REPO_FULL_NAME }}
          echo ${{ needs.get-pr-sha.outputs.PR_HEAD_REPO_OWNER }}
          echo ${{ needs.get-pr-sha.outputs.PR_BASE_REPO_OWNER }}
          echo ${{ needs.get-pr-sha.outputs.PR_HEAD_REPO_NAME }}
          echo ${{ needs.get-pr-sha.outputs.PR_BASE_REPO_NAME }}
          echo ${{ needs.get-pr-sha.outputs.PR_HEAD_REF }}
          echo ${{ needs.get-pr-sha.outputs.PR_BASE_REF }}
          echo ${{ needs.get-pr-sha.outputs.PR_HEAD_SHA }}
          echo ${{ needs.get-pr-sha.outputs.PR_BASE_SHA }}
          echo ${{ needs.get-pr-sha.outputs.PR_MERGE_COMMIT_SHA }}
          echo ${{ needs.get-pr-sha.outputs.PR_HEAD_COMMIT_DATE }}
          echo ${{ needs.get-pr-sha.outputs.PR_MERGE_COMMIT_DATE }}
          echo ${{ needs.get-pr-sha.outputs.PR_HEAD_COMMIT_TIMESTAMP }}
          echo ${{ needs.get-pr-sha.outputs.PR_MERGE_COMMIT_TIMESTAMP }}
#          echo ${{ needs.get-pr-sha.outputs.PR }}

  verity_pr_commit:
    name: Verity PR commit corresponds to a specific event by comparing timestamps
    runs-on: ubuntu-22.04
    needs: get-pr-sha
    env:
#      COMMENT_TIMESTAMP: 1751143805
#      COMMENT_DATE: ${{ github.event.comment.created_at }}
      COMMENT_DATE: 2025-06-28T21:02:16Z
    steps:
      - run: |
          COMMENT_TIMESTAMP=$(date -d "${COMMENT_DATE}" +"%s")
          echo $COMMENT_TIMESTAMP
          echo $PR_MERGE_COMMIT_TIMESTAMP
          if [ $COMMENT_TIMESTAMP -le $PR_MERGE_COMMIT_TIMESTAMP ]; then
            echo "Last commit on the pull request is newer than the issue comment triggering this run! Abort!";
            exit -1;
          fi
