name: Dummy
on:
  pull_request:


jobs:
  get-pr-number:
    name: Get PR number
    uses: ./.github/workflows/self-get-pr-number.yml

  show-pr-number:
    runs-on: ubuntu-latest
    needs: get-pr-number
    steps:
      - run: echo ${{ needs.get-pr-number.outputs.PR_NUMBER }}

  get-pr-sha:
    name: Get PR commit SHA
    needs: get-pr-number
    if: ${{ needs.get-pr-number.outputs.PR_NUMBER != ''}}
    uses: ./.github/workflows/self-get-pr-sha.yml
    with:
      pr_number: ${{ needs.get-pr-number.outputs.PR_NUMBER }}

  show-pr-sha:
    runs-on: ubuntu-latest
    needs: get-pr-sha
    steps:
      - run: |
          echo ${{ needs.get-pr-sha.outputs.PR_HEAD_SHA_BAD }}
          echo ${{ needs.get-pr-sha.outputs.PR_MERGE_SHA_BAD }}
          echo ${{ needs.get-pr-sha.outputs.PR_HEAD_REPO_FULL_NAME }}
          echo ${{ needs.get-pr-sha.outputs.PR_HEAD_REF }}
          echo ${{ needs.get-pr-sha.outputs.PR_BASE_REF }}
          echo ${{ needs.get-pr-sha.outputs.PR_HEAD_SHA }}
          echo ${{ needs.get-pr-sha.outputs.PR_BASE_SHA }}
          echo ${{ needs.get-pr-sha.outputs.PR_MERGE_SHA }}
          echo ${{ needs.get-pr-sha.outputs.PR }}