name: Dummy
on:
  pull_request:


jobs:
  get-pr-number:
    name: Get PR number
    uses: ./.github/workflows/self-get-pr-number.yml

  show-pr-number:
    runs-on: ubuntu-latest
    needs: get-pr-number
    steps:
      - run: echo ${{ needs.get-pr-number.outputs.PR_NUMBER }}
